import {
  type DiscountBenefit,
  type DiscountDuration,
  type ProviderDiscount,
  ProviderNormalizationError,
  normalizeCurrency,
  stripReservedKeys,
} from '@its-just-billing/provider-sdk';
import type Stripe from 'stripe';
import { fromUnixSeconds } from '../clone-date.js';

function benefitOf(coupon: Stripe.Coupon): DiscountBenefit {
  if (coupon.percent_off !== null) {
    return { kind: 'percent', percentOff: coupon.percent_off };
  }
  if (coupon.amount_off !== null && coupon.currency !== null) {
    return {
      kind: 'amount',
      amountOff: {
        amount: coupon.amount_off,
        currency: normalizeCurrency(coupon.currency),
      },
    };
  }
  throw new ProviderNormalizationError({
    message: `Stripe coupon ${coupon.id} has neither percent_off nor amount_off+currency`,
  });
}

function durationOf(coupon: Stripe.Coupon): DiscountDuration {
  if (coupon.duration === 'forever') return { kind: 'forever' };
  if (coupon.duration === 'once') return { kind: 'once' };
  if (coupon.duration === 'repeating' && coupon.duration_in_months !== null) {
    return { kind: 'repeating', months: coupon.duration_in_months };
  }
  throw new ProviderNormalizationError({
    message: `Stripe coupon ${coupon.id} has unrecognized duration shape`,
  });
}

/**
 * Reserved metadata key set on a PromotionCode whose `code` was
 * auto-generated by Stripe (i.e. the caller didn't supply one). On read the
 * normalizer surfaces `code: null` for such promotion codes so the round-trip
 * matches the SDK contract: "if you didn't ask for a code, you don't get one".
 */
export const ANONYMOUS_CODE_MARKER_KEY = '__provider_anonymous_code';

/**
 * Reserved metadata keys for round-tripping `restrictedTo`. Stripe's native
 * coupon supports restriction by product only (`applies_to.products`) and
 * rejects unknown product ids. The SDK contract treats `restrictedTo` as
 * caller-supplied state that round-trips through the API, not as an enforced
 * restriction. Stash the values in managed metadata so the round-trip works
 * regardless of whether the referenced products exist on Stripe, and read
 * from there in the normalizer (falling back to `applies_to.products` for
 * dashboard-created coupons that don't have the marker).
 */
export const RESTRICTED_PRODUCT_IDS_KEY = '__provider_restricted_products';
export const RESTRICTED_PRICE_IDS_KEY = '__provider_restricted_prices';

/**
 * Stripe discount = `PromotionCode` (the customer-facing redeemable) +
 * its underlying `Coupon`. ProviderDiscount.id is the PromotionCode id;
 * benefit/duration come from the embedded Coupon. The Coupon is required to
 * be expanded (`expand: ['coupon']`) — Stripe always returns it on
 * PromotionCode reads since the type is `Stripe.Coupon` (not a reference).
 */
function parseIdList(value: string | undefined): string[] | undefined {
  if (!value) return undefined;
  // Stored as JSON array of strings (so order is preserved and we can
  // distinguish "empty list" from "absent" if needed).
  try {
    const parsed = JSON.parse(value);
    return Array.isArray(parsed) && parsed.every((s) => typeof s === 'string') ? parsed : undefined;
  } catch {
    return undefined;
  }
}

function restrictedToOf(pc: Stripe.PromotionCode): ProviderDiscount['restrictedTo'] {
  // Prefer the SDK-managed metadata; this is how we round-trip values that
  // Stripe's native applies_to can't represent (priceIds, or productIds that
  // don't exist on the account).
  const productIds = parseIdList(pc.metadata?.[RESTRICTED_PRODUCT_IDS_KEY]);
  const priceIds = parseIdList(pc.metadata?.[RESTRICTED_PRICE_IDS_KEY]);
  if (productIds !== undefined || priceIds !== undefined) {
    const out: { productIds?: string[]; priceIds?: string[] } = {};
    if (productIds !== undefined) out.productIds = productIds;
    if (priceIds !== undefined) out.priceIds = priceIds;
    return out;
  }
  // Fall back to native applies_to for dashboard-created / pre-marker coupons.
  const nativeProducts = pc.coupon.applies_to?.products ?? [];
  return nativeProducts.length > 0 ? { productIds: [...nativeProducts] } : null;
}

export function normalizeStripePromotionCode(
  pc: Stripe.PromotionCode,
): ProviderDiscount<Stripe.PromotionCode> {
  const coupon = pc.coupon;
  const isAnonymousCode = pc.metadata?.[ANONYMOUS_CODE_MARKER_KEY] === '1';
  return {
    id: pc.id,
    code: isAnonymousCode ? null : pc.code,
    benefit: benefitOf(coupon),
    duration: durationOf(coupon),
    active: pc.active,
    expiresAt: pc.expires_at !== null ? fromUnixSeconds(pc.expires_at) : null,
    redemptionLimit: pc.max_redemptions,
    redemptionCount: pc.times_redeemed,
    restrictedTo: restrictedToOf(pc),
    metadata: stripReservedKeys(pc.metadata ?? {}),
    createdAt: fromUnixSeconds(pc.created),
    raw: pc,
  };
}
