import {
  type DiscountBenefit,
  type DiscountDuration,
  type ProviderDiscount,
  ProviderNormalizationError,
  normalizeCurrency,
  stripReservedKeys,
} from '@its-just-billing/provider-sdk';
import type Stripe from 'stripe';
import { fromUnixSeconds } from '../clone-date.js';

function benefitOf(coupon: Stripe.Coupon): DiscountBenefit {
  if (coupon.percent_off !== null) {
    return { kind: 'percent', percentOff: coupon.percent_off };
  }
  if (coupon.amount_off !== null && coupon.currency !== null) {
    return {
      kind: 'amount',
      amountOff: {
        amount: coupon.amount_off,
        currency: normalizeCurrency(coupon.currency),
      },
    };
  }
  throw new ProviderNormalizationError({
    message: `Stripe coupon ${coupon.id} has neither percent_off nor amount_off+currency`,
  });
}

function durationOf(coupon: Stripe.Coupon): DiscountDuration {
  if (coupon.duration === 'forever') return { kind: 'forever' };
  if (coupon.duration === 'once') return { kind: 'once' };
  if (coupon.duration === 'repeating' && coupon.duration_in_months !== null) {
    return { kind: 'repeating', months: coupon.duration_in_months };
  }
  throw new ProviderNormalizationError({
    message: `Stripe coupon ${coupon.id} has unrecognized duration shape`,
  });
}

/**
 * Reserved metadata key set on a PromotionCode whose `code` was
 * auto-generated by Stripe (i.e. the caller didn't supply one). On read the
 * normalizer surfaces `code: null` for such promotion codes so the round-trip
 * matches the SDK contract: "if you didn't ask for a code, you don't get one".
 */
export const ANONYMOUS_CODE_MARKER_KEY = '__provider_anonymous_code';

/**
 * Reserved metadata key for round-tripping price-scoped `restrictedTo`.
 *
 * Restriction splits by what Stripe can enforce natively with zero extra
 * round-trips (the discriminator for mimic-vs-capability):
 *
 *  - **Product** scope → Stripe's native `coupon.applies_to.products`. The
 *    adapter sets it directly (one field on the create call) and reads it
 *    back, so `capabilities.features.discountProductRestrictions` is `true`.
 *    Stripe rejects product ids that don't exist on the account — that's
 *    honest native enforcement, not something we paper over.
 *  - **Price** scope → Stripe has no native mechanism. We round-trip the
 *    value in managed metadata so it isn't lost, but the adapter does not
 *    enforce it; `capabilities.features.discountPriceRestrictions` is `false`
 *    and the consumer enforces it from its own persistence.
 */
export const RESTRICTED_PRICE_IDS_KEY = '__provider_restricted_prices';

/**
 * Legacy reserved key. Before product restriction moved to native
 * `coupon.applies_to`, the adapter stashed `restrictedTo.productIds` in this
 * promotion-code metadata key and never set native `applies_to`. We no longer
 * *write* it, but discounts created by the old code carry product ids only
 * here — read it as a fallback so those round-trip instead of silently
 * becoming `restrictedTo: null`. Native `applies_to` (the new source of
 * truth) takes precedence when present.
 */
const LEGACY_RESTRICTED_PRODUCT_IDS_KEY = '__provider_restricted_products';

/**
 * Stripe discount = `PromotionCode` (the customer-facing redeemable) +
 * its underlying `Coupon`. ProviderDiscount.id is the PromotionCode id;
 * benefit/duration come from the embedded Coupon. The Coupon is required to
 * be expanded (`expand: ['coupon']`) — Stripe always returns it on
 * PromotionCode reads since the type is `Stripe.Coupon` (not a reference).
 */
function parseIdList(value: string | undefined): string[] | undefined {
  if (!value) return undefined;
  // Stored as JSON array of strings (so order is preserved and we can
  // distinguish "empty list" from "absent" if needed).
  try {
    const parsed = JSON.parse(value);
    return Array.isArray(parsed) && parsed.every((s) => typeof s === 'string') ? parsed : undefined;
  } catch {
    return undefined;
  }
}

function restrictedToOf(pc: Stripe.PromotionCode): ProviderDiscount['restrictedTo'] {
  // Product scope: native applies_to is the source of truth (the adapter
  // writes it there and Stripe enforces it). Stripe omits the embedded
  // coupon's `applies_to` from a PromotionCode response unless
  // `expand: ['coupon.applies_to']` is requested — the discounts domain does
  // exactly that on every read (a same-request expand, zero extra round
  // trips; empirically required and accepted by the live API, contrary to it
  // looking like a non-expandable sub-object). Fall back to the legacy
  // metadata key for discounts created before the move to native applies_to.
  const nativeProducts = pc.coupon.applies_to?.products ?? [];
  const productIds =
    nativeProducts.length > 0
      ? [...nativeProducts]
      : parseIdList(pc.metadata?.[LEGACY_RESTRICTED_PRODUCT_IDS_KEY]);
  // Price scope: round-tripped via managed metadata (Stripe has no native
  // price restriction). Not enforced by the adapter.
  const priceIds = parseIdList(pc.metadata?.[RESTRICTED_PRICE_IDS_KEY]);
  if (productIds === undefined && priceIds === undefined) return null;
  const out: { productIds?: string[]; priceIds?: string[] } = {};
  if (productIds !== undefined) out.productIds = productIds;
  if (priceIds !== undefined) out.priceIds = priceIds;
  return out;
}

export function normalizeStripePromotionCode(
  pc: Stripe.PromotionCode,
): ProviderDiscount<Stripe.PromotionCode> {
  const coupon = pc.coupon;
  const isAnonymousCode = pc.metadata?.[ANONYMOUS_CODE_MARKER_KEY] === '1';
  return {
    id: pc.id,
    code: isAnonymousCode ? null : pc.code,
    benefit: benefitOf(coupon),
    duration: durationOf(coupon),
    active: pc.active,
    expiresAt: pc.expires_at !== null ? fromUnixSeconds(pc.expires_at) : null,
    redemptionLimit: pc.max_redemptions,
    redemptionCount: pc.times_redeemed,
    restrictedTo: restrictedToOf(pc),
    metadata: stripReservedKeys(pc.metadata ?? {}),
    createdAt: fromUnixSeconds(pc.created),
    raw: pc,
  };
}
